id: I7C0CF11C
ocr_import_info:
  timestamp: '2023-09-23T04:57:14.943751+00:00'
  batch_id: batch-46bb
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-23 05:02:46.087775+00:00
last_modified: 2023-09-23 05:02:46.087783+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1164
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1164
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟེན་འབྲེལ་བསྟོད་པའི་ཊིཀྐ་རིན་ཆེན་ལྗོན་ཤིང་སོགས།
  languages:
  - bo
  author: དཀོན་མཆོག་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9408095191759241
  ocr_word_median_confidence_index: 0.9908183
bases:
  I1NLM1164_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1164_001
      total_pages: 264
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1164_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9908183
      ocr_word_mean_confidence_index: 0.9408095191759241
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
